In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader.data as web
import datetime as dt
import calendar
import csv

## 1.  資料匯入

In [2]:
tickers = ['EWA', 'EWZ', 'EWC', 'FXI', 'EWQ', 'EWG', 'EWH', 'EWI', 'EWJ', 'EWY',
           'EWN', 'EWS', 'EZA', 'EWP', 'EWD', 'EWL', 'EWT', 'EWU', 'IVV']

In [3]:
data = pd.read_csv("data_firsthalf.csv", index_col=0 )
data.index = pd.to_datetime(data.index)
data.head()

,EWA,EWZ,EWC,FXI,EWQ,EWG,EWH,EWI,EWJ,EWY,EWN,EWS,EZA,EWP,EWD,EWL,EWT,EWU,IVV
Date,,,,,,,,,,,,,,,,,,,
2005-01-03,8.217886,14.126711,12.931461,13.237745,16.154015,13.303169,7.709301,31.728643,34.990158,23.648851,12.649429,7.995531,23.410761,19.021193,12.767601,12.915568,15.704612,20.224211,88.355942
2005-01-04,8.073186,13.520161,12.553794,12.872897,15.789632,13.037824,7.522993,31.005836,34.406452,23.001278,12.464212,7.859820,22.539045,18.658321,12.447660,12.509844,15.347388,19.853024,87.292419
2005-01-05,8.103125,13.402760,12.387615,12.580059,15.809880,13.044994,7.355958,31.167849,34.374020,23.157021,12.381896,8.006838,21.926809,18.555410,12.441620,12.509844,15.281234,19.864275,86.764305
2005-01-06,8.118093,13.285370,12.319633,12.594460,15.769397,13.052168,7.426626,31.142916,34.374020,22.771757,12.416193,8.153857,21.282505,18.642071,12.465767,12.524873,15.268003,19.853024,87.116364
2005-01-07,8.108113,13.467980,12.289425,12.481648,15.722158,12.966111,7.349532,30.818907,34.179440,22.706182,12.278999,8.040765,21.396206,18.241280,12.314852,12.284440,15.148928,19.875515,86.954994

In [4]:
change = data - data.shift(1)
change.head()

,EWA,EWZ,EWC,FXI,EWQ,EWG,EWH,EWI,EWJ,EWY,EWN,EWS,EZA,EWP,EWD,EWL,EWT,EWU,IVV
Date,,,,,,,,,,,,,,,,,,,
2005-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-04,-0.144700,-0.606550,-0.377667,-0.364848,-0.364383,-0.265346,-0.186309,-0.722807,-0.583706,-0.647573,-0.185217,-0.135711,-0.871716,-0.362871,-0.319941,-0.405725,-0.357224,-0.371187,-1.063522
2005-01-05,0.029939,-0.117401,-0.166179,-0.292838,0.020248,0.007171,-0.167035,0.162012,-0.032433,0.155743,-0.082316,0.147017,-0.612236,-0.102911,-0.006041,0.000000,-0.066154,0.011251,-0.528114
2005-01-06,0.014968,-0.117390,-0.067982,0.014400,-0.040483,0.007174,0.070669,-0.024933,0.000000,-0.385263,0.034297,0.147019,-0.644304,0.086660,0.024147,0.015029,-0.013231,-0.011251,0.352058
2005-01-07,-0.009979,0.182611,-0.030209,-0.112811,-0.047238,-0.086057,-0.077094,-0.324009,-0.194580,-0.065575,-0.137194,-0.113092,0.113701,-0.400791,-0.150915,-0.240433,-0.119075,0.022491,-0.161369

In [5]:
returns = (data - data.shift(1)) / data.shift(1)
returns.head()

,EWA,EWZ,EWC,FXI,EWQ,EWG,EWH,EWI,EWJ,EWY,EWN,EWS,EZA,EWP,EWD,EWL,EWT,EWU,IVV
Date,,,,,,,,,,,,,,,,,,,
2005-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-04,-0.017608,-0.042936,-0.029205,-0.027561,-0.022557,-0.019946,-0.024167,-0.022781,-0.016682,-0.027383,-0.014642,-0.016973,-0.037236,-0.019077,-0.025059,-0.031414,-0.022746,-0.018354,-0.012037
2005-01-05,0.003708,-0.008683,-0.013237,-0.022748,0.001282,0.000550,-0.022203,0.005225,-0.000943,0.006771,-0.006604,0.018705,-0.027163,-0.005516,-0.000485,0.000000,-0.004310,0.000567,-0.006050
2005-01-06,0.001847,-0.008759,-0.005488,0.001145,-0.002561,0.000550,0.009607,-0.000800,0.000000,-0.016637,0.002770,0.018362,-0.029384,0.004670,0.001941,0.001201,-0.000866,-0.000566,0.004058
2005-01-07,-0.001229,0.013745,-0.002452,-0.008957,-0.002996,-0.006593,-0.010381,-0.010404,-0.005661,-0.002880,-0.011050,-0.013870,0.005342,-0.021499,-0.012106,-0.019196,-0.007799,0.001133,-0.001852

## 2. 兩種觀點下的long-short portfolio

### 技術指標1：14日RSI

In [6]:
def cal_rsi(series):    #series: data["ticker"]
    up_days = series[series > 0]
    down_days = series[series < 0]
    up = up_days.mean() if len(up_days) > 0 else 0
    down = abs(down_days.mean()) if len(down_days) > 0 else 0
    return 100 * up / (up + down)

In [7]:
rsi = pd.DataFrame()
for i in tickers:
    rsi[i] = change[i].rolling(14).agg(cal_rsi)   #14d-RSI
rsi

,EWA,EWZ,EWC,FXI,EWQ,EWG,EWH,EWI,EWJ,EWY,EWN,EWS,EZA,EWP,EWD,EWL,EWT,EWU,IVV
Date,,,,,,,,,,,,,,,,,,,
2005-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-24,43.925192,50.028769,56.464688,51.436498,34.206727,19.354933,44.642937,37.681392,38.802458,49.458478,39.751205,43.657170,32.360935,48.356899,33.355301,37.009265,49.038495,21.758163,46.447657
2005-01-25,53.207678,59.492796,65.464731,58.220904,44.149094,21.951245,53.202039,47.058872,42.352888,60.855986,44.444261,50.380482,34.947605,47.607170,34.857308,47.851645,52.121262,30.275030,46.351486
2005-01-26,58.178925,58.660613,68.406671,65.878221,47.236026,28.600510,59.805809,48.000065,41.715554,63.119779,53.225888,49.904301,37.918105,55.806743,38.114942,50.555624,54.767699,44.117376,45.043891
2005-01-27,62.021569,55.701740,70.009517,69.497492,44.868507,30.872450,59.758535,45.188355,43.558286,71.162547,51.666738,44.827582,41.883009,59.105605,42.431605,53.846154,53.460658,40.106811,43.166595
2005-01-28,55.555660,54.091050,69.038711,71.593563,42.501745,32.394323,63.258818,45.736172,44.654053,65.455855,59.047691,46.697344,45.448099,66.259848,45.177845,59.052142,52.674948,42.522027,42.632451
2005-01-31,54.811849,53.329238,68.246505,73.998888,49.570374,34.426201,63.949770,47.955260,44.999857,67.462950,61.835161,43.478394,41.882944,68.459723,41.621705,57.057611,59.649203,48.717926,45.396018
2005-02-01,57.312277,48.418892,67.695359,73.407855,48.111138,39.189054,66.019288,56.826081,41.221460,69.700863,65.085430,46.083223,42.527499,67.732616,45.491762,52.469106,59.649203,60.747975,46.641655
2005-02-02,56.275415,49.172272,63.587121,70.074439,46.783719,38.356275,68.491407,47.297007,40.310163,71.926213,64.655267,47.107500,45.328978,63.366338,43.073048,48.837186,62.702754,61.051098,46.240423
2005-02-03,57.836349,49.006820,62.566884,71.078704,44.692750,40.345825,66.709923,46.153736,38.235333,70.600868,60.483875,47.107303,49.039146,59.813099,41.605838,51.219537,64.804468,70.160828,50.617550
2005-02-04,58.695767,49.903996,66.477306,70.400455,50.543526,43.339412,66.883891,47.776133,34.883699,68.065299,58.164361,45.064484,48.710593,59.675957,39.849477,44.954160,66.666692,71.670493,53.398182
2005-02-07,63.529360,52.747374,65.000102,69.484030,56.225006,46.037057,69.035525,51.949982,40.079997,64.415577,58.665240,45.762792,50.708381,57.925018,42.152552,46.531766,64.804397,69.828220,52.999739
2005-02-08,64.285885,48.529370,62.184859,66.884759,61.403752,46.268596,68.030733,53.845912,45.127552,71.891861,68.726783,48.387084,53.712545,56.184009,38.860037,49.197931,68.690165,76.415567,57.435227
2005-02-09,64.285812,59.615506,69.158918,64.171980,68.965602,47.987638,72.677487,55.851080,51.103634,67.285006,67.367249,56.603702,56.975024,64.476849,48.145387,48.022699,66.221957,73.432405,55.312839
2005-02-10,67.347022,59.231781,75.187914,65.125077,68.235505,49.295749,76.878565,62.100253,49.913259,64.735508,66.539994,51.470725,53.858331,59.701787,46.631955,53.299386,63.924718,76.005986,59.604001
2005-02-11,67.213223,58.731303,73.684228,63.783896,70.735830,53.505578,76.785867,61.983196,53.846154,66.265049,69.444476,54.272736,53.306733,55.958836,45.936417,45.390040,66.210290,77.032991,57.483548
2005-02-14,63.730715,49.453988,73.443874,61.271910,69.512236,55.358715,77.387040,58.577263,55.413963,63.881351,70.060640,50.777014,58.380316,57.685362,51.118191,42.238184,71.353675,74.712924,64.108334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-11-16,35.934215,58.778726,36.065540,47.368421,47.154320,35.235867,40.585686,47.570298,52.594108,39.695980,52.102572,25.414715,42.346695,45.534763,38.554324,60.897611,37.001885,58.510563,37.505413
2012-11-19,40.885319,59.851031,41.887763,53.699831,57.700632,46.843144,45.303280,57.644672,53.398057,48.076124,55.394314,32.539757,43.851420,48.448711,53.443929,68.674679,37.125761,62.295030,43.351673
2012-11-20,44.680929,53.765130,42.870700,51.889664,53.353613,47.484786,45.958897,58.044405,55.555381,48.338214,55.942595,32.539724,49.170105,46.201631,58.441444,75.313791,41.778937,57.446894,37.782507
2012-11-21,47.840604,46.706519,41.982542,45.549135,49.393472,45.282961,40.106856,53.389792,51.648389,50.150611,49.052091,32.539861,50.921841,41.621542,56.403306,71.993726,39.352606,51.473090,31.718465
2012-11-23,56.569279,48.583326,46.687717,50.000000,55.141747,54.012359,41.516216,61.410801,52.823261,50.717676,59.420338,40.259926,49.160956,49.484670,63.363636,76.429759,49.107079,57.926756,34.879228
2012-11-26,59.528891,53.075697,46.394955,52.996997,57.334714,50.335522,45.812929,63.519300,52.823261,54.742570,55.263101,39.473762,51.660974,47.629789,64.835954,75.556786,48.532668,57.142857,40.743573
2012-11-27,53.333442,52.847521,47.826031,53.441437,57.341619,53.846154,45.575297,61.197399,57.142802,50.000000,52.558094,43.846217,50.897590,46.287849,62.566895,78.104906,51.176397,56.722619,40.953735
2012-11-28,54.978479,49.139872,49.337783,60.000059,63.157953,58.870616,50.741737,64.360899,56.772822,54.264331,55.617870,46.956507,47.160368,52.896219,62.835311,79.693014,51.851837,61.005328,50.144737
2012-11-29,53.117213,51.897599,49.090879,61.049635,65.217316,59.715986,54.832475,72.826017,55.737750,58.372833,57.722912,51.522232,51.272215,62.755148,60.992996,77.714271,54.826193,64.556972,54.812271
2012-11-30,52.941176,52.830153,54.452084,57.967528,64.660644,59.459530,59.795346,72.432339,58.620908,63.789492,53.068566,53.167394,48.731676,60.448990,60.352639,74.521509,52.244868,59.767923,57.645529
2012-12-03,52.763764,54.461173,59.942373,59.789943,62.947480,59.459503,59.090767,71.977935,62.962973,61.671285,53.237396,54.893563,55.415642,57.079425,60.612893,72.586844,56.707336,53.822898,60.164221
2012-12-04,55.343353,58.141038,62.089563,62.174759,61.436232,62.099246,61.538107,70.076270,62.962991,69.404463,46.633669,54.430466,55.051599,59.086392,62.972562,70.018546,61.428611,51.162724,62.005395
2012-12-05,68.676913,68.269263,69.456130,67.346759,59.900572,64.946996,65.732618,66.043010,70.833598,76.226615,42.930392,64.000096,64.058359,62.053686,58.801766,69.546117,63.133599,60.512656,69.214468
2012-12-06,69.533371,65.662769,71.711520,61.903000,62.787657,65.676172,65.901149,67.117001,67.816262,77.856065,39.393883,65.986474,65.423225,59.523948,54.639691,73.352389,62.264081,62.365485,66.350358
2012-12-07,72.095973,63.185826,69.924885,62.381894,67.835696,67.895576,66.067971,66.816011,62.162256,76.114958,76.471346,69.325186,61.578234,50.000278,54.985627,80.689296,62.616781,60.512560,66.182823
2012-12-10,67.394534,60.754732,65.576735,59.723830,61.937225,62.477651,66.037470,60.439535,58.098796,71.319643,79.190212,72.519200,60.000052,47.477909,48.686037,75.903239,66.037648,54.166382,56.080259
2012-12-11,76.923016,63.699881,61.837494,59.616842,63.210201,63.778296,65.825225,58.407054,59.567378,73.021888,79.660544,70.803186,59.999793,52.419513,40.361415,68.845264,60.591191,53.332980,59.488122
2012-12-12,64.864902,64.062615,62.822665,58.297242,63.575689,64.516183,63.485409,59.656703,61.644135,75.601133,79.428105,71.631509,62.725395,55.509124,42.785167,68.571336,70.108677,53.614213,59.122165
2012-12-13,50.207247,59.842444,56.183854,51.561032,59.999735,56.856894,52.892403,53.921551,55.556111,72.093455,72.033222,67.479955,62.969643,48.245659,34.156316,65.216846,58.333272,46.153908,48.843894
2012-12-14,42.320523,58.037033,55.017511,51.954252,59.302313,58.038329,52.789659,51.780816,56.250571,83.980535,74.999558,67.480022,57.742438,49.953035,34.291498,65.624639,60.176964,43.686157,45.020011
2012-12-17,43.477793,68.725725,59.837951,55.872615,66.200931,53.521137,55.656027,54.053995,61.905280,84.999985,80.445407,65.625310,57.070644,54.756463,39.736198,75.673603,58.874481,45.807097,52.393554
2012-12-18,41.482988,71.760091,59.192820,45.645547,65.536506,54.639169,58.286482,53.927296,68.525943,83.848055,78.968382,63.262738,61.523752,57.166284,40.356681,74.283673,55.872343,46.327550,54.991126
2012-12-19,46.308619,73.537239,57.453744,55.759741,61.962174,62.393008,61.532726,50.183228,70.154918,82.706902,77.978930,55.887426,64.327000,55.752112,40.356773,71.872705,41.132256,41.881820,50.895617
2012-12-20,47.110898,76.762200,54.771278,55.549464,64.331579,62.231628,61.166626,45.065496,72.036656,78.918981,80.223062,56.388868,83.003343,58.188290,41.911523,71.794116,39.705347,44.608191,51.281425
2012-12-21,41.422684,64.224327,48.692418,50.707815,60.218294,57.627063,60.658847,50.326826,68.730107,52.248578,57.587861,49.816862,68.686347,54.298241,45.867166,50.226100,33.607374,30.579452,46.868290
2012-12-24,44.098530,62.385098,48.127415,56.068141,54.906493,57.839232,61.517645,49.982356,70.906157,50.091844,59.180638,48.664731,66.135500,51.356394,48.903715,48.844699,33.265432,29.910822,45.599299
2012-12-26,49.590926,59.709144,51.506481,49.188991,58.712156,58.435242,54.139482,46.890660,73.972986,52.653414,60.022127,51.921059,65.329716,43.011250,46.965990,50.479105,34.097203,33.933618,48.404772
2012-12-27,51.219312,59.505424,57.730808,48.360473,61.634834,58.630257,51.946131,47.618601,72.802260,50.330975,64.787656,51.976068,65.561923,44.733984,50.436056,56.451256,37.525266,32.641178,53.049439
2012-12-28,48.950680,62.271204,56.517561,46.952384,47.449690,49.446203,55.960593,45.046058,70.434601,52.699448,54.228136,45.984104,65.230403,36.474298,47.193823,50.226125,40.591378,31.103697,51.067866
2012-12-31,58.831211,63.474819,59.911796,52.368023,55.011095,56.352462,58.617152,51.516376,69.448389,58.247202,56.518934,42.943407,67.587089,35.201969,52.413772,55.644964,42.530648,39.636039,60.277831

#### 以2005/1的RSI大小排名出前四檔和後四檔ETF，做成兩個投資組合

2005/1 前段四檔：EWT, EWY, FXI, EWC (H2L)
<br/>       後段四檔：EWG, EZA, EWU, EWD (L2H)

In [8]:
type(data.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [56]:
monthly_rsi = rsi.asfreq('BM')
monthly_rsi.head()

,EWA,EWZ,EWC,FXI,EWQ,EWG,EWH,EWI,EWJ,EWY,EWN,EWS,EZA,EWP,EWD,EWL,EWT,EWU,IVV
Date,,,,,,,,,,,,,,,,,,,
2005-01-31,54.811849,53.329238,68.246505,73.998888,49.570374,34.426201,63.949770,47.955260,44.999857,67.462950,61.835161,43.478394,41.882944,68.459723,41.621705,57.057611,59.649203,48.717926,45.396018
2005-02-28,63.956957,64.414759,74.766957,60.990755,70.408030,50.867252,70.156929,55.659527,54.617262,65.469837,80.344743,51.428389,64.904960,46.239017,56.591531,78.983095,58.510674,57.778050,45.652412
2005-03-31,33.243676,54.273630,60.866267,34.511977,32.251639,34.999975,42.241325,52.366365,25.925706,32.459692,55.681914,32.025979,46.837648,54.765506,39.416125,36.590793,20.864306,29.323508,40.594628
2005-04-29,36.320350,48.108148,42.594376,62.814685,44.461973,45.895622,62.179540,25.531558,53.781592,52.351549,45.110759,47.572835,39.586798,43.985176,42.506683,46.206780,47.959302,46.101801,42.927466
2005-05-31,43.783878,54.834213,48.780408,29.360484,46.631995,46.849333,46.153846,40.909216,40.908916,41.360994,38.002921,56.896484,32.902273,51.336467,41.260825,60.818658,55.714284,49.382931,59.586123

### 抓出每個月RSI前四和後四檔的ETF

In [59]:
'''
#抓出每個月RSI前四和後四檔ETF(會print出2005~2012每個月的8檔，但沒有另外開空間存起來)
for i in range(len(monthly_rsi)):
    #每月rsi排名
    temp_rsi_set = monthly_rsi.ix[i, :]   #type: pd.series
    print(monthly_rsi.index[i])
    #print(type(temp_rsi_set))
    monthly_rsi_set = []
    for j in range(len(temp_rsi_set)):
        etf_rsi = [monthly_rsi.columns[j], temp_rsi_set[j]]
        monthly_rsi_set.append(etf_rsi)
    monthly_rsi_set.sort(key=lambda x: x[1], reverse=True)
    print(monthly_rsi_set)
    #取出每月前四檔和後四檔etf名稱
    long_4_etf = [k[0] for k in monthly_rsi_set[:4]]
    short_4_etf = [l[0] for l in monthly_rsi_set[-4:]]
    print(long_4_etf)
    print(short_4_etf)
    print("")'''

'''
#算出portfolio的單月return
monthly_long_ret = []
monthly_short_ret = []
for i in range(4):
    temp_long_ret = returns['2005-1'][long_4_etf[i]].mean()
    temp_short_ret = returns['2005-1'][short_4_etf[i]].mean()
    monthly_long_ret.append(temp_long_ret)
    monthly_short_ret.append(temp_short_ret)

monthly_port_ret = np.mean(monthly_long_ret) - np.mean(monthly_short_ret)
print(monthly_port_ret)'''

"\n#算出portfolio的單月return\nmonthly_long_ret = []\nmonthly_short_ret = []\nfor i in range(4):\n    temp_long_ret = returns['2005-1'][long_4_etf[i]].mean()\n    temp_short_ret = returns['2005-1'][short_4_etf[i]].mean()\n    monthly_long_ret.append(temp_long_ret)\n    monthly_short_ret.append(temp_short_ret)\n\nmonthly_port_ret = np.mean(monthly_long_ret) - np.mean(monthly_short_ret)\nprint(monthly_port_ret)"

### 寫成函數

In [57]:
def get_8_etf_rsi(time):   #time: "y-m" ex."2005-1"   #output: 兩個list(long, short)
    temp_rsi_set = monthly_rsi[time]   #type: pd.dataframe
    #print(temp_rsi_set)
    #print(monthly_rsi.index[i])
    monthly_rsi_set = []   #每個月的etf排名及其rsi值
    for j in range(temp_rsi_set.shape[1]):   #df行數
        etf_rsi = [tickers[j], temp_rsi_set.iloc[0, j]]   #ix: label or index searching
        monthly_rsi_set.append(etf_rsi)
    monthly_rsi_set.sort(key=lambda x: x[1], reverse=True)
    #print(monthly_rsi_set)
    #取出每月前四檔和後四檔etf名稱
    long_4_etf = [k[0] for k in monthly_rsi_set[:4]]
    short_4_etf = [l[0] for l in monthly_rsi_set[-4:]]
    return long_4_etf, short_4_etf

def monthly_portfolio_return_rsi(time, long_4_etf, short_4_etf):
    monthly_long_ret = []
    monthly_short_ret = []
    for i in range(4):
        temp_long_ret = returns[time][long_4_etf[i]].mean()
        temp_short_ret = returns[time][short_4_etf[i]].mean()
        monthly_long_ret.append(temp_long_ret)
        monthly_short_ret.append(temp_short_ret)

    monthly_port_ret = np.mean(monthly_long_ret) - np.mean(monthly_short_ret)
    return monthly_port_ret

In [58]:
etf = get_8_etf_rsi("2005-1")
print(etf)
monthly_return = monthly_portfolio_return_rsi('2005-1', etf[0], etf[1])
print(monthly_return)

(['FXI', 'EWP', 'EWC', 'EWY'], ['EWS', 'EZA', 'EWD', 'EWG'])
0.0020173027790087034

### testing area

In [89]:
returns['2005-1']["EWA"].mean()

0.001190991022144487

In [48]:
for i in range(2,6):
    print(i)
    
tmp = monthly_rsi["2005-1"]
print(tmp)
print(type(tmp.ix[0,3]))
print(tmp.shape[1])

2
3
4
5

### 使用函數跑每月的資料（2005-1~2012-12)

In [60]:
all_ret_rsi = []
all_etf_rsi = []
for y in range(2005, 2013):
    for d in range(1, 13):
        time = str(y)+'-'+str(d)
        #print(time)
        tmp_etf = get_8_etf_rsi(time)
        tmp_ret = monthly_portfolio_return_rsi(time, tmp_etf[0], tmp_etf[1])
        all_etf_rsi.append(tmp_etf)
        all_ret_rsi.append(tmp_ret)

#print(all_etf_rsi)
mean_rsi = np.mean(all_ret_rsi)
print(mean_rsi)

0.000955828484310077

<b/>以RSI作為投資組合選擇指標，蒐集每月的報酬率（Rp_大 - Rp_小），則84個月的平均報酬率為0.096%。

### 技術指標2：5日MA